[phases.setup]
nixPkgs = ["python313", "python313Packages.pip", "postgresql"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "streamlit run rag_web.py --server.port=$PORT --server.address=0.0.0.0"
